name: "Go - Build and Test"

on:
  push:
    paths: ['**.go']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          TEST_VARS: ${{ secrets.TEST_VARS }}
        run: |
          mkdir -p ./pkg/testdata/emptydir
          go get github.com/joho/godotenv/cmd/godotenv
          godotenv -f ${{ env.TEST_VARS }} go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Upload coverage to Codecov
        run:
          bash <(curl -s https://codecov.io/bash)
