name: "Go - Build and Test"

on:
  push:
    paths: ['**.go']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          bot_token: ${{ secrets.ENV_BOT_TOKEN }}
          bot_chat: ${{ secrets.ENV_BOT_CHAT }}
        run: |
          mkdir -p ./pkg/testdata/emptydir
          ENV_BOT_TOKEN=${{ env.bot_token }} ENV_BOT_CHAT=${{ env.bot_chat }} go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Upload coverage to Codecov
        run:
          bash <(curl -s https://codecov.io/bash)
